create table if not exists endpoint_hits
(
    id       int generated by default as identity primary key,
    app      varchar   not null,
    uri      varchar   not null,
    ip       varchar   not null,
    hit_time timestamp not null
);